### ISSUE TITLE
Unable to use nx-web-ext with TS 5.x

### ISSUE THREAD

**Issue by Jack-Barry** [spaceribs/spaceribs#121]
I tried to update to latest, but in my project I'm using `typescript` @ `5.0.4`

Since the `typescript` and `rxjs` dependencies are now locked to a specific minor version (`~` instead of `^`), it's a no-go.

Any reason the change was made to lock down to a specific minor version of those dependencies?

**Comment by spaceribs** [comment]
@Jack-Barry thanks for the heads up! I usually just try to match whatever is in the root, and in this case I think it was a bit too specific. Let me adjust it now and republish
