### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by work933k** [spaceribs/spaceribs#263]
Hi!

I notice that sometimes our CI-pipeline fails, while running the same commands locally on the same code succeeds.
If i then locally remove the Betterer-cache files in the tmp-folder and rerun the commands locally (with --skip-nx-cache) i also get the same errors as in our CI-pipeline. This makes me come to the conclusion that in some situations the caching will get "out-of-sync". Maybe this only happens when working with multiple team-members or something.

In our CI-pipeline the tmp-folder is not persisted, thus the cache-files will not be present. While on the dev-machines the tmp-folder is persisted. I think this would mean that the problem is not the NX-cache, but Betterer incorrectly re-uses the cache-files when they are in the tmp-folder.

My current solution/work-around is that i have removed the "Betterer"-tasks (nx.json "cacheableOperations") from being cached by NX. 

Thanks!

**Comment by spaceribs** [comment]
Should be solved in https://github.com/spaceribs/spaceribs/releases/tag/nx-betterer-3.0.1
