### ISSUE TITLE
Nx betterer task succeed when using precommit even though there are errors

### ISSUE THREAD

**Issue by alaa0000** [spaceribs/spaceribs#266]
`nx betterer project --precommit` should fail if the tests got worse.
[Here](https://github.com/spaceribs/spaceribs/blob/main/packages/nx-betterer/src/executors/betterer/executor.ts#L90), it's not checking for the result, it should be like this:
<img width="1194" alt="Screenshot 2024-04-22 at 2 54 04 PM" src="https://github.com/spaceribs/spaceribs/assets/24501151/474a0bc7-0153-43d0-901d-fd18b7b08710">

**Comment by spaceribs** [comment]
I'll look into this, I think I ran into the same bug on a private project and I did come up with a similar fix...

**Comment by spaceribs** [comment]
@alaa0000 Try the latest version (3.0.2) with the following changes:
1. Remove the precommit configuration across the board, if you have any sort of release process you can remove it entirely and just run betterer with no special configuration. I have an [example here of how to accomplish this](https://github.com/spaceribs/spaceribs/blob/main/.github/workflows/release.yml#L35-L42).
2. Update anything calling `--update` to `--forceUpdate`, want to be clearer that this is only really to be used when you'd like to override betterer.
